namespace UiChallenges.Common
{
	// Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
	static class IconFont
	{
		public const string HeartOutline = "\U000f02d5";
		public const string Heart = "\U000f02d1";
		public const string Star = "\U000f04ce";
	}
}
